### ISSUE TITLE
Installer on Debian 7.6

### ISSUE THREAD

**Issue by lindleyw** [AlliumCepa/webgui#10]
two minor and one major:
- in curses installer, sudo password is echoed in plaintext and remains on screen during installation.
- Error messages during apt-get stomp all over screen layout
- On bare Debian 7.6 system, following instructions, installer goes into infinite loop with apt-get complaints like:
  
  percona-server-server-5.5 : Depends: percona-server-client-5.5 (>= 5.5.38-rel35.2-674.squeeze) but it is not going to be installed
  Depends: libssl0.9.8 (>= 0.9.8m-1) but it is not installable
  E: Unable to correct problems, you have held broken packages.

**Comment by scrottie** [comment]
Just did a bunch of work on the installer for Debian.  CentOS is broken, and OSX very probably is too.
Reading through here, the one thing I know I didn't fix on Debian is accepting an empty password for MySQL.  Oh, that and not letting people try to create a root user to run wG as.  I was also only testing on one version, and a Docker image of it at that.

**Comment by scrottie** [comment]
Installer perl is dead in favor of docker images.  Running upgrader scripts (needed even on a new 8.0 install) continues to be crabby but some work on the docker build process has improved that.  At least this way, the devs get stuck with that and other things.  Closing this.  Thank you everyone for your reports and help.
