### ISSUE TITLE
Centos install ExtUtils/MakeMaker.pm

### ISSUE THREAD

**Issue by dannymk** [AlliumCepa/webgui#30]
I know the Centos install is broken however did not see this issue listed:

installer: perl webgui_installer.pl
Can't locate ExtUtils/MakeMaker.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Makefile.PL line 13.
BEGIN failed--compilation aborted at Makefile.PL line 13.
make: **\* No rule to make target `/home/scott/lib/perl5/5.12.3/i686-linux/Config.pm', needed by`Makefile'.  Stop.
Can't locate Curses.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at webgui_installer.pl line 289.
BEGIN failed--compilation aborted at webgui_installer.pl line 345.

**Comment by scrottie** [comment]
Last I tried it, it was at least stopping and warning people that it was broken.  Thanks for the report.

**Comment by dannymk** [comment]
You are welcome.  I am working on the admin interface.  Do you want me to use the NewAdminInterface branch?

**Comment by scrottie** [comment]
That's good news!

Sure.  I'm working on master on http://webgui.org/alliumcepa/webgui, but the changes aren't structural at all, so I don't think we'll conflict.

I did add some JSON RPC endpoints that would be useful for the new admin as I was re-adding wgpkg package import/export features to Doug's admin.

**Comment by dannymk** [comment]
We need simplified JSON objects returned from the server.  We can't continue to support the interface the way it is built.  It is waay too slow and no one will maintain that code.  I can probably have a pretty good prototype by the time YAPC comes this year.  Let me get the one I have working and we can go from there.

**Comment by scrottie** [comment]
Then we should try to merge branches.  The AlliumCepa branch has an older version of new admin in it already.

**Comment by scrottie** [comment]
From IRC discussion:

and if anyone wants to help get CentOS going on the installer again, that
would be keen.  I got stuck when MariaDB refused to start and figured out
that the mysql_install_db distributed in the mysql_server package was
incompatible with the mysqld in the same package.
last time I tried to fix CentOS, I couldn't get it to recognize any network
cards.  so either I'm cursed, or CentOS is having serious issues.

**Comment by scrottie** [comment]
Since originally opening this, RedHat has done an enormous amount of work in breaking POSIX and Unix compatibility and dealing with the hell that is a half-baked Unix knock-off doing its best impression of a proprietary ex-Unix flying off in to left has lost any incentive thanks to Docker where is merely buggy and clunky so I'm closing this as Will Not Fix.
