### ISSUE TITLE
Docker "entrypoint" and "user"

### ISSUE THREAD

**Issue by dannymk** [AlliumCepa/webgui#37]
On line 135 the file refers to "share/entrypoint" when it should just be "entrypoint" as the entry point file is in the root directory of the project and not under the share directory.

Line 141 should be changed to:  "USER webgui" as a best practice.  We do not want docker containers running users as root.

**Comment by scrottie** [comment]
Fixed in dcd2709e19e7cdc689eeaf7846da20283642e934 and 7da14d4840be169f69ed2fde01d8cc94cc856126.  Failed to commit a file move and set the wg docker container to run as 'webgui' as requested.
